linkshare/config/routes.rb
Linkshare::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]
  get 'users/form_test' => 'users#form_test'
  resources :groups do
    member do
      get 'join'
      get 'leave'
    end
  end
  resources :shares
  root 'users#index'

end

linkshare/app/views/partials/_embedly.html.erb
<%= link_to link.url do %>
  <div class="small-10 large-10 columns link_content">
    <div class='small-4 large-4 columns'>
      <%= image_tag link.img_url %>
    </div>
    <div class="small-8 large-8 columns">
      <div class="row">
        <h3><%= link.title %><h3>
        <h4>Description: <%= link.description %></h4>
      </div>
    </div>
  </div>
<%end%>

linkshare/app/views/partials/_log_in.html.erb
<%= form_for("user", :url => user_session_path) do |f| %>
  <%= f.text_field :email %>
  <%= f.password_field :password %>
  <%= f.check_box :remember_me %>
  <%= f.label :remember_me %>
  <%= f.submit 'Sign in' %>
  <%= link_to "Forgot your password?", new_password_path('user') %>
<% end %>

linkshare/app/views/partials/_logo_link.html.erb
<%= link_to image_tag('linksharelogo.png'),root_path, target: '_blank', :class => "logo_big" %>

linkshare/app/views/partials/_navigation.html.erb
<nav class="top-bar">
<ul class="inline-list">
<li><%= link_to "Home", root_path %></li>
<li><%= link_to "Groups", groups_path %></li>
<li><%= link_to "Shares", shares_path  %></li>
<li><% if current_user %>
<%= link_to "logout", destroy_user_session_path, :method => :delete %>
<% else %>
<%= link_to "sign in", new_user_session_path %>
<% end %></li>
</ul>
</nav>