linkshare/config/routes.rb
Linkshare::Application.routes.draw do

  devise_for :users
  resources :users, only: [:index]
  get 'users/form_test' => 'users#form_test'
  resources :groups do
    member do
      get 'join'
      get 'leave'
    end
  end
  resources :shares
  root 'users#index'

end

linkshare/app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :network
  has_many :shares
  #has_many :tags

  validates_uniqueness_of :name, scope: :network_id, :unless => :solo?
  # function to get X number of popular groups


  validate :valid_network

  def valid_network
    errors.add(:network_id, "Network is not valid") unless Network.find_by_id(self.network_id)
  end

def find_owner
    if self.solo?
      self.users.where(:my_group => self.id).first
    end
  end

end

linkshare/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	# add group owner to group entry.  Only this user can edit group
	# before filter only: destroy isOwner
  before_filter :authenticate_user!

  def index
  # display list of groups for user to add
  # should be ordered by most relevant/popular
    @groups = Group.where(:network_id=>current_user).order(:name)
  end

  def show
		# displays group information
    unless @group = Group.find_by_id(params[:id])
      redirect_to :back, notice: "This group does not exist"
    end
    if @group.solo?
      @link_hash = @group.find_owner.get_owner_links
    end
  end

  def new
		# Generate form for group creator to fill out
		@group = Group.new()
	end

	def create
		# save group in database
		@group = Group.new(group_params)
    @group.network_id = current_user.network_id
		if @group.save
			redirect_to @group
		else
			render 'new'
		end
  end


  def edit
		# provides same form as new
		# need to add group
		@group = Group.find_by(id: params[:id])
	end

	def update
		# saves data from edit
		@group = Group.find_by(id: params[:id])
		if @group.update(group_params)
     redirect_to @group
   else
    render 'edit'
    end
  end

  def destroy
		# removes group from database
		# eventually removes all entries from usergroups table
    @group = Group.find_by(id: params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def join
    @group = Group.find_by(id: params[:id])
    @group.update_attributes(user_ids: current_user.id)
    @group.save
    redirect_to @group
  end

  def leave
    @group=Group.find_by(id: params[:id])
    @group.users.delete(User.find current_user.id)
    redirect_to @group
  end

  private
  def group_params
    params.require(:group).permit(:network_id,:name,:description,:img_url)
  end

end

linkshare/app/helpers/groups_helper.rb
module GroupsHelper
end

linkshare/app/views/groups/index.html.erb
<h4>Don't see the group your looking for?  Add one <%= link_to "Here", new_group_path %></h4>

<h1>List of Groups</h1>

<ul>
  <% @groups.each do |g| %>
    <li><%= link_to g.name, g %></li>
  <% end %>
</ul>

linkshare/app/views/groups/new.html.erb
<h1>Fill me out to make a group</h1>
<%= form_for @group do |f| %>
  <div class="row">
    <div class="large-4 columns"><%= f.label "Group Name" %><%= f.text_field :name %></div>
  </div>
  <div class="row">
    <div class="large-4 columns"><%= f.label "Group Description" %><%= f.text_area :description %></div>
  </div>
  <div class="row">
    <div class="large-2 columns"><%= f.button %></div>
  </div>
<% end %>

linkshare/app/views/groups/show.html.erb
<% if @group.solo? %>
  <% group_name = @group.name.split("@").first %>
  <h1>Welcome to <%= group_name %>'s Linkshare</h1>
<% else %>
  <h1>Welcome to the <%= @group.name %> Group</h1>
<%end%>

<div class="row display">
<div class="small-4 large-4 columns"><%= @group.description %></div>
</div>
<div class="row">
  <% if @group.solo? %>
    <% @link_hash.each do |l, a| %>
      <div class="row shares">
          <%= render partial: "partials/embedly", locals: {link: l} %>
      </div>
  <% end %>
  <% else %>
    <%if !(@group.users.find_by_id(current_user.id))%>
      <%= link_to 'join', join_group_path(@group), :class=>"button small" %>
    <%else%>
      <%= link_to 'leave', leave_group_path(@group), :class=>"button small" %>
    <%end%>
    
      <% @group.shares.each do |s| %>
        <div class="row shares">
        <div class="small-2 large-2 columns">
          <%= link_to s.user.email, group_path(:id => s.user.my_group)%>
        </div>
        
          <%= render partial: "partials/embedly", locals: {link: s.link} %>
        </div>
      <%end%>
  <%end%>
</div>